# Random password for ClickHouse
# Using a alphanumeric password to avoid issues with special characters on bash entrypoint
resource "random_password" "clickhouse_password" {
  length      = 64
  special     = false
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
}

locals {
  # Deploy ClickHouse into the EKS cluster unless an external one is configured
  deploy_clickhouse = var.external_clickhouse == null
}

# cert-manager issues the TLS certificates for the ClickHouse operator's
# admission webhooks. Only required while ClickHouse runs in-cluster.
resource "helm_release" "cert_manager" {
  count = local.deploy_clickhouse ? 1 : 0

  name             = "cert-manager"
  repository       = "https://charts.jetstack.io"
  chart            = "cert-manager"
  version          = var.cert_manager_chart_version
  namespace        = "cert-manager"
  create_namespace = true

  values = [<<EOT
crds:
  enabled: true
EOT
  ]

  # Every Fargate pod is a cold micro-VM with no local image cache, so the
  # three cert-manager deployments regularly need longer than the provider's
  # default 300s to all report ready.
  timeout = 600

  depends_on = [
    aws_eks_fargate_profile.namespaces,
  ]
}

# Official ClickHouse Kubernetes operator. The Langfuse Helm chart v2 renders
# ClickHouseCluster and KeeperCluster resources that this operator reconciles.
# Both CRD sets (cert-manager and the operator) must exist before the Langfuse
# chart is installed.
resource "helm_release" "clickhouse_operator" {
  count = local.deploy_clickhouse ? 1 : 0

  name             = "clickhouse-operator"
  repository       = "oci://ghcr.io/clickhouse"
  chart            = "clickhouse-operator-helm"
  version          = var.clickhouse_operator_chart_version
  namespace        = "clickhouse-operator-system"
  create_namespace = true

  # Same Fargate cold start, and the operator only becomes ready once
  # cert-manager has issued its webhook certificate. The Langfuse chart below
  # needs the operator's CRDs and webhook to already exist.
  timeout = 600

  depends_on = [
    helm_release.cert_manager,
    aws_eks_fargate_profile.namespaces,
  ]
}

# EFS Access Points for Clickhouse instances
resource "aws_efs_access_point" "clickhouse" {
  count          = local.deploy_clickhouse ? var.clickhouse_replicas : 0
  file_system_id = aws_efs_file_system.langfuse[0].id

  root_directory {
    path = "/clickhouse/${count.index}"
    creation_info {
      owner_gid   = 1001
      owner_uid   = 1001
      permissions = "0755"
    }
  }

  posix_user {
    gid = 1001
    uid = 1001
  }

  tags = {
    Name = "${local.tag_name} Clickhouse"
  }
}

# EFS Access Points for ClickHouse Keeper instances
resource "aws_efs_access_point" "keeper" {
  count          = local.deploy_clickhouse ? var.clickhouse_keeper_replicas : 0
  file_system_id = aws_efs_file_system.langfuse[0].id

  root_directory {
    path = "/keeper/${count.index}"
    creation_info {
      owner_gid   = 1001
      owner_uid   = 1001
      permissions = "0755"
    }
  }

  posix_user {
    gid = 1001
    uid = 1001
  }

  tags = {
    Name = "${local.tag_name} Keeper"
  }
}

# Create the Clickhouse PVs. The claim names match the PVCs generated by the
# ClickHouse operator for the ClickHouseCluster named "langfuse":
# <volume template>-<cluster>-clickhouse-<shard>-<replica>-<ordinal>
resource "kubernetes_persistent_volume" "clickhouse_data" {
  count = local.deploy_clickhouse ? var.clickhouse_replicas : 0

  metadata {
    name = "clickhouse-data-${count.index}"
  }

  spec {
    capacity = {
      storage = var.clickhouse_storage_size
    }
    volume_mode                      = "Filesystem"
    access_modes                     = ["ReadWriteOnce"]
    persistent_volume_reclaim_policy = "Retain"
    storage_class_name               = kubernetes_storage_class.efs[0].metadata[0].name
    persistent_volume_source {
      csi {
        driver        = "efs.csi.aws.com"
        volume_handle = "${aws_efs_file_system.langfuse[0].id}::${aws_efs_access_point.clickhouse[count.index].id}"
      }
    }
    claim_ref {
      name      = "clickhouse-storage-volume-langfuse-clickhouse-0-${count.index}-0"
      namespace = "langfuse"
    }
  }

  depends_on = [
    kubernetes_storage_class.efs,
  ]
}

resource "kubernetes_persistent_volume" "clickhouse_keeper" {
  count = local.deploy_clickhouse ? var.clickhouse_keeper_replicas : 0

  metadata {
    name = "clickhouse-keeper-${count.index}"
  }

  spec {
    capacity = {
      storage = var.clickhouse_keeper_storage_size
    }
    volume_mode                      = "Filesystem"
    access_modes                     = ["ReadWriteOnce"]
    persistent_volume_reclaim_policy = "Retain"
    storage_class_name               = kubernetes_storage_class.efs[0].metadata[0].name
    persistent_volume_source {
      csi {
        driver        = "efs.csi.aws.com"
        volume_handle = "${aws_efs_file_system.langfuse[0].id}::${aws_efs_access_point.keeper[count.index].id}"
      }
    }
    claim_ref {
      name      = "clickhouse-storage-volume-langfuse-keeper-${count.index}-0"
      namespace = "langfuse"
    }
  }

  depends_on = [
    kubernetes_storage_class.efs,
  ]
}
